-- CREATE DATABASE SPMEDICALGROUP_MANHA

-- USE SPMEDICALGROUP_MANHA


CREATE TABLE CLINICAS(
	ID INT IDENTITY PRIMARY KEY,
	RAZAO_SOCIAL VARCHAR(200) NOT NULL,
	NOME_FANTASIA VARCHAR(200) NOT NULL,
	CNPJ CHAR(12) NOT NULL,
	LOGRADOURO VARCHAR(200) NOT NULL,
	NUMERO INT NOT NULL,
	BAIRRO VARCHAR(200) NOT NULL,
	CIDADE VARCHAR(200) NOT NULL,
	ESTADO VARCHAR(200) NOT NULL,
);

CREATE TABLE CREDENCIAIS(
	ID INT IDENTITY PRIMARY KEY,
	CREDENCIAL VARCHAR(200) NOT NULL,
);

CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY,
	EMAIL VARCHAR(200) NOT NULL,
	SENHA VARCHAR(200) NOT NULL,
	ID_CREDENCIAL INT FOREIGN KEY REFERENCES CREDENCIAIS(ID),
);

CREATE TABLE PACIENTES(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(200) NOT NULL,
	RG CHAR(9) NOT NULL,
	CPF CHAR(11) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	TELEFONE VARCHAR(11),
	LOGRADOURO VARCHAR(200) NOT NULL,
	NUMERO INT NOT NULL,
	BAIRRO VARCHAR(200) NOT NULL,
	CIDADE VARCHAR(200) NOT NULL,
	ESTADO VARCHAR(200) NOT NULL,
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID),
);

CREATE TABLE ESPECIALIDADES(
	ID INT IDENTITY PRIMARY KEY,
	ESPECIALIDADE VARCHAR(200) NOT NULL,
);

CREATE TABLE MEDICOS(
	ID INT IDENTITY PRIMARY KEY,
	CRM CHAR(7) NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID),
	ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID),
	ID_CLINICA INT FOREIGN KEY REFERENCES CLINICAS(ID),
);

CREATE TABLE STATUS_CONSULTA(
	ID INT IDENTITY PRIMARY KEY,
	SITUACAO VARCHAR(200) NOT NULL,
);

CREATE TABLE CONSULTAS(
	ID INT IDENTITY PRIMARY KEY,
	DESCRICAO TEXT,
	DATA_CONSULTA DATE NOT NULL,
	HORA_CONSULTA TIME NOT NULL,
	ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTES(ID),
	ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID),
	ID_STATUS INT FOREIGN KEY REFERENCES STATUS_CONSULTA(ID) DEFAULT 1
);

