SELECT * FROM USUARIOS
SELECT * FROM CREDENCIAIS
SELECT * FROM CLINICAS
SELECT * FROM ESPECIALIDADES
SELECT * FROM MEDICOS
SELECT * FROM PACIENTES
SELECT * FROM STATUS_CONSULTA
SELECT * FROM CONSULTAS

--Mostrou a quantidade de usuários após realizar a importação do banco de dados
SELECT COUNT (ID) AS Quantidade_suários
FROM USUARIOS;

--Converteu a data de nascimento do usuário para o formato 
SELECT convert(varchar, getdate(), 101)	 DATA_NASCIMENTO FROM PACIENTES

SELECT EMAIL, CREDENCIAL FROM USUARIOS INNER JOIN CREDENCIAIS ON USUARIOS.ID_CREDENCIAL = CREDENCIAIS.ID